version: '3.7'
services:
 myapp:
  image: petclinic
  ports:
    - 1010:8080
  environment:
    SPRING_PROFILES_ACTIVE: mysql
  depends_on:
    - petdb
 
 petdb:
  image: mysql:5.7
  ports:
   - 3306:3306
  volumes:
   - db_vol:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: petclinic
    MYSQL_PASSWORD: petclinic
    MYSQL_DATABASE: petclinic
 
 petdb-backup:
  image: petdb_backup
  tty: true
  volumes:
    - db_backup:/backup
  depends_on:
    - petdb 

volumes:
 db_vol:
 db_backup:
